'use client'

import React from "react";

import styles from "../components/sass_components/FooterBanner.module.scss";
import Square from "@/shapes/Square";

const FooterBanner = () => {

  return (
    <div className={styles.footer_banner}>

      <div className={styles.column}>
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
      </div>
      <div className={styles.column}>
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
      </div>
      <div className={styles.column}>
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true}  isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true}  isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={true} isWhite={false} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
      </div>
      <div className={styles.column}>
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
      </div>
      <div className={styles.column}>
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
      </div>
      <div className={styles.column}>
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
        <Square isTransparent={false} isWhite={true} />
      </div>
 
    </div>
  );
};

export default FooterBanner;
